Repository morelinq/MoreLINQ, pull requests merged in 2018-05, with the labels that each got.

#478 Use TestingSequence in Insert tests
  MoreLinq.Test/InsertTest.cs
Labels: Component-Tests

#476 Optimize ScanRight for IReadOnlyList #128
  MoreLinq.Test/ScanRightTest.cs
  MoreLinq/ScanRight.cs
Labels: enhancement

#481 Fix eclint-ing in CI build 🚧
  appveyor.yml
Labels: Component-Scripts

#479 Add AwaitCompletion for await “tasks”
  MoreLinq/Experimental/Await.cs
  MoreLinq/MoreLinq.csproj
  README.md
Labels: enhancement, experimental

#497 Added ToListLike to avoid repetitive code
  MoreLinq/AggregateRight.cs
  MoreLinq/ListLike.cs
  MoreLinq/ScanRight.cs
Labels: refactoring

#487 Use SourceKind instead of ToBreaking* in tests
  MoreLinq.Test/BreakingCollection.cs
  MoreLinq.Test/BreakingList.cs
  MoreLinq.Test/CompareCountTest.cs
  MoreLinq.Test/CountDownTest.cs
  MoreLinq.Test/EndsWithTest.cs
  MoreLinq.Test/FallbackIfEmptyTest.cs
  MoreLinq.Test/MemoizeTest.cs
  MoreLinq.Test/SliceTest.cs
  MoreLinq.Test/StartsWithTest.cs
  MoreLinq.Test/TakeLastTest.cs
  MoreLinq.Test/TestExtensions.cs
Labels: refactoring
