Repository morelinq/MoreLINQ, pull requests merged in 2018-04, with the labels that each got.

#205 Await: asynchronous evaluation of sequence elements
  MoreLinq.Test/MoreLinq.Test.csproj
  MoreLinq.Test/NullArgumentTest.cs
  MoreLinq/Experimental/Await.cs
  MoreLinq/MoreLinq.csproj
  README.md
Labels: enhancement, experimental

#444 Use value tuples to reduce allocations in TagFirstLast
  MoreLinq/TagFirstLast.cs
Labels: enhancement, performance

#449 Optimize EndsWith false case for collections
  MoreLinq.Test/EndsWithTest.cs
  MoreLinq/EndsWith.cs
Labels: enhancement, performance

#446 Added missing tests on PreScan
  MoreLinq.Test/PreScanTest.cs
Labels: Component-Tests

#451 Replace delegate for BreakingFunc on tests
  MoreLinq.Test/AssertTest.cs
  MoreLinq.Test/EquiZipTest.cs
  MoreLinq.Test/ScanTest.cs
  MoreLinq.Test/ZipLongestTest.cs
  MoreLinq.Test/ZipShortestTest.cs
Labels: Component-Tests

#455 Use var in XML doc examples for less type ceremony
  MoreLinq/Generate.cs
  MoreLinq/Pad.cs
  MoreLinq/Pairwise.cs
  MoreLinq/PreScan.cs
  MoreLinq/Prepend.cs
  MoreLinq/Scan.cs
  MoreLinq/TakeEvery.cs
  MoreLinq/TakeLast.cs
Labels: docs

#457 Much simplified (lazy) NestedLoop implementation
  MoreLinq.Test/BreakingAction.cs
  MoreLinq.Test/MoreLinq.Test.csproj
  MoreLinq.Test/NestedLoopTest.cs
  MoreLinq/NestedLoops.cs
Labels: refactoring

#473 Make empty sequence checks consistent in tests
  MoreLinq.Test/CartesianTest.cs
  MoreLinq.Test/ExcludeTest.cs
  MoreLinq.Test/InterleaveTest.cs
  MoreLinq.Test/MaxByTest.cs
  MoreLinq.Test/MinByTest.cs
  MoreLinq.Test/ScanTest.cs
  MoreLinq.Test/SegmentTest.cs
  MoreLinq.Test/SequenceTest.cs
  MoreLinq.Test/SkipLastTest.cs
  MoreLinq.Test/SkipUntilTest.cs
  MoreLinq.Test/TakeEveryTest.cs
  MoreLinq.Test/TakeLastTest.cs
  MoreLinq.Test/UnfoldTest.cs
  MoreLinq.Test/WindowedTest.cs
Labels: Component-Tests
