Repository morelinq/MoreLINQ, pull requests merged in 2018-06, with the labels that each got.

#512 Upgrade to .NET Core SDK 2.1.200
  .travis.yml
  global.json
Labels: Component-Scripts

#519 Fixed typo in Readme.md
  README.md
Labels: docs

#235 Conflict-free extensions generator
  MoreLinq.sln
  MoreLinq/Extensions.ToDataTable.g.cs
  MoreLinq/Extensions.g.cs
  MoreLinq/MoreLinq.csproj
  MoreLinq/PartialSort.cs
  MoreLinq/PreScan.cs
  MoreLinq/Scan.cs
  README.md
  appveyor.yml
  bld/ExtensionsGenerator/MoreLinq.ExtensionsGenerator.csproj
  bld/ExtensionsGenerator/Program.cs
  build.cmd
  build.sh
  global.json
Labels: enhancement
