Repository morelinq/MoreLINQ, pull requests merged in 2020-08, with the labels that each got.

#751 Replace explicit type mentions with object pattern
  MoreLinq.Test/AggregateTest.cs
  MoreLinq.Test/ChooseTest.cs
  MoreLinq/AssertCount.cs
  MoreLinq/Backsert.cs
  MoreLinq/CountDown.cs
  MoreLinq/CountMethods.cs
  MoreLinq/EndsWith.cs
  MoreLinq/Experimental/Await.cs
  MoreLinq/Experimental/TrySingle.cs
  MoreLinq/FallbackIfEmpty.cs
  MoreLinq/Flatten.cs
  MoreLinq/PadStart.cs
  MoreLinq/SkipLast.cs
  MoreLinq/StartsWith.cs
  MoreLinq/TakeLast.cs
Labels: refactoring

#750 Optimize Batch for empty IReadOnlyCollection<T> too
  MoreLinq.Test/BatchTest.cs
  MoreLinq/Batch.cs
Labels: enhancement

#754 Update to .NET Core SDK 3.1
  .travis.yml
  MoreLinq.Test/MoreLinq.Test.csproj
  bld/ExtensionsGenerator/MoreLinq.ExtensionsGenerator.csproj
  global.json
Labels: Component-Scripts

#756 Update .NET Core installation script
  appveyor.yml
  tools/dotnet-install.ps1
Labels: Component-Scripts

#757 Fix (bash) test script to test against .NET Core 3.1
  test.sh
Labels: Component-Scripts

#755 Update all test dependencies
  .config/dotnet-tools.json
  .travis.yml
  MoreLinq.Test/MoreLinq.Test.csproj
  appveyor.yml
Labels: Component-Tests
