Repository morelinq/MoreLINQ, pull requests merged in 2020-12, with the labels that each got.

#772 Fix typo in Partition return value documentation
  MoreLinq/Extensions.g.cs
  MoreLinq/Partition.cs
Labels: docs

#776 Integrate templated code generation into project file
  MoreLinq/MoreLinq.csproj
  MoreLinq/tt.cmd
  MoreLinq/tt.sh
  build.cmd
  build.sh
Labels: Component-Scripts

#777 Add .NET 5.0 as a test target
  .travis.yml
  MoreLinq.Test/MoreLinq.Test.csproj
  appveyor.yml
  test.cmd
  test.sh
Labels: Component-Tests

#779 Disable parallel building due to T4 for simplicity
  MoreLinq/MoreLinq.csproj
  build.cmd
  build.sh
Labels: Component-Scripts

#778 Unify to single CI platform
  .travis.yml
  appveyor.yml
  tools/dotnet-install.sh
Labels: Component-Scripts
