Repository morelinq/MoreLINQ, pull requests merged in 2023-11, with the labels that each got.

#1035 Update test packages to latest versions
  MoreLinq.Test/MoreLinq.Test.csproj
Labels: Component-Tests

#1049 Refactor `RandomSubset` internals for DRY, removing closure
  MoreLinq/RandomSubset.cs
  MoreLinq/Shuffle.cs
Labels: refactoring

#1037 Introduce `Duplicates` extension
  MoreLinq.Test/DuplicatesTest.cs
  MoreLinq/Duplicates.cs
  MoreLinq/Extensions.g.cs
  MoreLinq/MoreLinq.csproj
  MoreLinq/PublicAPI/net6.0/PublicAPI.Unshipped.txt
  MoreLinq/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  MoreLinq/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  MoreLinq/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
  README.md
  bld/Copyright.props
Labels: enhancement

#1052 Refactor `Subsets` core into an iterator method
  MoreLinq.Test/SubsetTest.cs
  MoreLinq/Subsets.cs
Labels: refactoring
