Repository morelinq/MoreLINQ, pull requests merged in 2023-01, with the labels that each got.

#728 Add more `Interleave` tests
  MoreLinq.Test/InterleaveTest.cs
Labels: Component-Tests

#925 Use tuples to perform swap in `Permutations`
  MoreLinq/Permutations.cs
Labels: refactoring

#927 Fix exception thrown by current buffer index implementation
  MoreLinq.Test/BatchTest.cs
  MoreLinq/Experimental/Batch.cs
Labels: bug

#926 Rewrite next permutation while-loop into a for-loop
  MoreLinq/Permutations.cs
Labels: refactoring

#942 Improve list optimisation in `CountDown`
  MoreLinq/CountDown.cs
Labels: performance

#472 List-like union as struct to save allocation + virtual dispatch
  MoreLinq/AggregateRight.cs
  MoreLinq/CountDown.cs
  MoreLinq/ListLike.cs
  MoreLinq/ScanRight.cs
Labels: performance, refactoring

#949 Consolidate structural differences in `*Like` types
  MoreLinq/CollectionLike.cs
  MoreLinq/ListLike.cs
  MoreLinq/MoreEnumerable.cs
Labels: refactoring

#958 Fix some doc comments
  MoreLinq/Extensions.g.cs
  MoreLinq/Interleave.cs
  MoreLinq/Lag.cs
  MoreLinq/Lead.cs
  MoreLinq/Permutations.cs
  MoreLinq/Slice.cs
  MoreLinq/SortedMerge.cs
  MoreLinq/Subsets.cs
  MoreLinq/Window.cs
Labels: docs
